### ISSUE TITLE
Cannot access to datasets.

### ISSUE THREAD

**Issue by wildgeece96** [zhenwang9102/X-MedRELA#1]
Hi, thank you for your interesting paper.

I want to reproduce your result using dataset you shared, but I couldn't download any of them.
Could you check the authorization of data on Google Drive?

**Comment by zhenwang9102** [comment]
> Hi, thank you for your interesting paper.
> 
> I want to reproduce your result using dataset you shared, but I couldn't download any of them.
> Could you check the authorization of data on Google Drive?

Thanks for your interest in the paper. I've shared the data with you. Please let me know if you have any problems with reproducing the results. Thanks!

**Comment by wildgeece96** [comment]
Thank you for quick action.
I could download them!
From now on, I will do the experiments. I may ask you something if there is a problem.

Thanks!
