### ISSUE TITLE
Other types of data

### ISSUE THREAD

**Issue by wildgeece96** [zhenwang9102/X-MedRELA#2]
I could reproduce the result of `treatment` relationship.

![image](https://user-images.githubusercontent.com/30517435/92298657-46297680-ef86-11ea-9585-cabd54aea11b.png)

I wonder if there are other data which has other relationship. Or can I produce them from `final_relation_triples_10rela.pkl` ?

And I want the data used in `user_sutdy.py`. Could you tell me where to get them?
Thanks.

**Comment by zhenwang9102** [comment]
Yes, the other types of relations you can try are contained in the relation file you mentioned, such as "causes", "prevents", etc.

The data for `user_study.py` is basically some mappings from strings to ids as well as your model prediction results. You can find the mappings in [the original medical cooc dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.jp917). Some of the processed data is also available in my [another repository](https://github.com/zhenwang9102/SurfCon).
